version: '3'

services: 

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile.dev
    container_name: flask_app_dev
    restart: always
    ports:
      - 5000:5000
    volumes: 
      - ./flask:/app
    environment: 
      - FLASK_APP=flask/app.py
      - FLASK_ENV=development